kind: Service
apiVersion: v1
metadata:
  name:  zookeeper-headless
  labels:
    app: zookeeper
spec:
  selector:
    app:  zookeeper
  ports:
  - name:  server
    port:  2888
  - name:  leader-election
    port:  3888
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  ports:
    - name: "client"
      port: 2181
  selector:
    app: zookeeper
