apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: poc:cluster-admin-group-binding
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""
subjects:
- kind: User
  name: pocAdmin
  apiGroup: rbac.authorization.k8s.io
- kind: ServiceAccount
  name: default
  apiGroup: rbac.authorization.k8s.io
