apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: poc:cluster-admin-group-binding
roleRef:
  kind: ClusterRole
  name: poc:cluster-admin-group-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: User
  name: pocAdmin
  apiGroup: rbac.authorization.k8s.io
