kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-zk-001
  labels:
    type: local
    app: zookeeper
spec:
  storageClassName: local-path
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/aranel/k8storage/zookeeper/disk001"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zk-pvc
spec:
  selector:
    matchLabels:
      app: zookeeper   
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes: [ "ReadWriteOnce" ]
