apiVersion: v1
kind: ConfigMap
metadata:
  name: zookeeper-cm
data:
  ALLOW_ANONYMOUS_LOGIN: "yes"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zookeeper
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: bitnami/zookeeper:3.7
          ports:
            - containerPort: 2181        
          env:
            - name: ALLOW_ANONYMOUS_LOGIN
              valueFrom:
                configMapKeyRef:
                  name: zookeeper-cm
                  key: ALLOW_ANONYMOUS_LOGIN
          resources:
          volumeMounts:
            - mountPath: /bitnami
              name: zk-pvc          
      restartPolicy: Always
      volumes:
        - name: zk-pvc
          persistentVolumeClaim:
            claimName: zk-pvc

