kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-kafka-001
  labels:
    type: local
    app: kafka
spec:
  storageClassName: local-path
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/aranel/k8storage/kafka/disk001"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-pvc
spec:
  selector:
    matchLabels:
      app: kafka   
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes: [ "ReadWriteOnce" ]