apiVersion: v1
kind: Namespace
metadata:
  name: kafka
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: zookeeper-policy
  namespace: kafka
spec:
  selector:
    matchLabels:
      app: zookeeper
  maxUnavailable: 1
